/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.netbeansfirebase;
 
import java.awt.HeadlessException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author t42131
 */
public class FormAdm extends javax.swing.JFrame {

    /**
     * Creates new form FormAdm
     */
    public FormAdm() {
        connection.connectioFirebase();
        initComponents();
        this.setLocationRelativeTo(null);
        PersonaProvide.cargarTablaPersona(tblG);
        txtFieldID.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblG = new javax.swing.JTable();
        txtNameLastName = new javax.swing.JLabel();
        txtDNI = new javax.swing.JLabel();
        txtEdad = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtFieldNameLastName = new javax.swing.JTextField();
        txtFieldDNI = new javax.swing.JTextField();
        txtFieldEdad = new javax.swing.JTextField();
        txtFieldEmail = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        txtFieldID = new javax.swing.JTextField();
        lblCatg = new javax.swing.JLabel();
        txtFieldRubro = new javax.swing.JTextField();
        lblIDCatg = new javax.swing.JLabel();
        txtFieldIDCatg = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCatg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblG);

        txtNameLastName.setText("Nombres y Apellidos");

        txtDNI.setText("DNI");

        txtEdad.setText("Edad");

        txtEmail.setText("Email");

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblID.setText("ID-Registro");

        txtFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldIDActionPerformed(evt);
            }
        });

        lblCatg.setText("Rubro");

        txtFieldRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldRubroActionPerformed(evt);
            }
        });

        lblIDCatg.setText("ID-Categ");

        txtFieldIDCatg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldIDCatgActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Datos de Usuarios\\t42131\\My Documents\\NetBeansProjects\\NetbeansFirebase\\src\\main\\java\\images\\foto-registro2.png")); // NOI18N

        btnCatg.setText("CATEGORIAS >>");
        btnCatg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(btnGuardar)
                                .addGap(70, 70, 70)
                                .addComponent(btnActualizar)
                                .addGap(73, 73, 73)
                                .addComponent(btnEliminar))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEmail)
                                            .addComponent(txtEdad)
                                            .addComponent(txtDNI)
                                            .addComponent(lblCatg)
                                            .addComponent(lblIDCatg)
                                            .addComponent(lblID))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                        .addContainerGap(55, Short.MAX_VALUE)
                                        .addComponent(txtNameLastName)
                                        .addGap(33, 33, 33)))
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFieldNameLastName)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                                .addComponent(txtFieldRubro))
                                            .addComponent(txtFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFieldIDCatg, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 128, Short.MAX_VALUE)))))
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCatg)
                                .addGap(121, 121, 121))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(jLabel1))
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(btnLimpiar)))
                                .addGap(32, 32, 32)))))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar))
                .addGap(31, 31, 31)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameLastName)
                    .addComponent(txtFieldNameLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDNI)
                                    .addComponent(txtFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEdad)
                                    .addComponent(txtFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEmail)
                                    .addComponent(txtFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCatg)
                                    .addComponent(txtFieldRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblIDCatg)
                                    .addComponent(txtFieldIDCatg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblID)
                            .addComponent(txtFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(btnCatg)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        actualizar();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldIDActionPerformed

    private void tblGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGMouseClicked
       int seleccion = tblG.getSelectedRow();
       txtFieldID.setText(tblG.getValueAt(seleccion, 0)+"");
       txtFieldNameLastName.setText(tblG.getValueAt(seleccion, 1)+"");
       txtFieldDNI.setText(tblG.getValueAt(seleccion, 2)+"");
       txtFieldEdad.setText(tblG.getValueAt(seleccion, 3)+"");
       txtFieldEmail.setText(tblG.getValueAt(seleccion, 4)+"");
       txtFieldRubro.setText(tblG.getValueAt(seleccion, 5)+"");
       txtFieldIDCatg.setText(tblG.getValueAt(seleccion, 6)+"");
    }//GEN-LAST:event_tblGMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        clearForm();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtFieldRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldRubroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldRubroActionPerformed

    private void txtFieldIDCatgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldIDCatgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldIDCatgActionPerformed

    private void btnCatgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatgActionPerformed
    CategoriasUsuarios form = new CategoriasUsuarios();
    form.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnCatgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCatg;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCatg;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIDCatg;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tblG;
    private javax.swing.JLabel txtDNI;
    private javax.swing.JLabel txtEdad;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JTextField txtFieldDNI;
    private javax.swing.JTextField txtFieldEdad;
    private javax.swing.JTextField txtFieldEmail;
    private javax.swing.JTextField txtFieldID;
    private javax.swing.JTextField txtFieldIDCatg;
    private javax.swing.JTextField txtFieldNameLastName;
    private javax.swing.JTextField txtFieldRubro;
    private javax.swing.JLabel txtNameLastName;
    // End of variables declaration//GEN-END:variables

    private void guardar() {
        int id = (int) (Math.random() * 100000);
        try {
            Map<String, Object> datos = new HashMap<>();
            datos.put("Nombres y Apellidos", txtFieldNameLastName.getText());
            datos.put("DNI", txtFieldDNI.getText());
            datos.put("Edad", txtFieldEdad.getText());
            datos.put("Email", txtFieldEmail.getText());
            datos.put("Rubro", txtFieldRubro.getText());
            datos.put("ID - Catg", txtFieldIDCatg.getText());
            PersonaProvide.guardarPersona("Persona", String.valueOf(id), datos);
            JOptionPane.showMessageDialog(null, "Guardado con Exito");
            clearForm();
        } catch (HeadlessException ex) {
            System.err.println("Error: " + ex.getMessage());
            JOptionPane.showMessageDialog(null, "Error al guardar");
        }
        finally{
        PersonaProvide.cargarTablaPersona(tblG);
        }
    }

    private void actualizar() {
        String idDoc = txtFieldID.getText();
        try {
            Map<String, Object> datos = new HashMap<>();
            datos.put("Nombres y Apellidos", txtFieldNameLastName.getText());
            datos.put("DNI", txtFieldDNI.getText());
            datos.put("Edad", txtFieldEdad.getText());
            datos.put("Email", txtFieldEmail.getText());
            datos.put("Rubro", txtFieldRubro.getText());
            datos.put("ID - Catg", txtFieldIDCatg.getText());
            PersonaProvide.actualizarPersona("Persona", idDoc, datos);
            JOptionPane.showMessageDialog(null, "Actualizado con Exito");
            clearForm();
        } catch (HeadlessException ex) {
            System.err.println("Error: " + ex.getMessage());
            JOptionPane.showMessageDialog(null, "Error al actualizar");
        }finally{
        PersonaProvide.cargarTablaPersona(tblG);
        }
    } 

    private void eliminar() {
        String idDoc = txtFieldID.getText();
        try {
            PersonaProvide.eliminarPersona("Persona", idDoc);
            JOptionPane.showMessageDialog(null, "Eliminado con Exito");
            clearForm();
        } catch (HeadlessException ex) {
            System.err.println("Error: " + ex.getMessage());
            JOptionPane.showMessageDialog(null, "Error al aliminar");
        } finally{
        PersonaProvide.cargarTablaPersona(tblG);
        }
    }

    void clearForm() {
        txtFieldID.setText("");
        txtFieldNameLastName.setText("");
        txtFieldDNI.setText("");
        txtFieldEdad.setText("");
        txtFieldEmail.setText("");
        txtFieldRubro.setText("");
        txtFieldIDCatg.setText("");
    }
}